const Menu = [
    {
      id:1,
      image:"Images/maggi.jpg",
      name: "maggi",
      category: "lunch",
      price:25,
      description:"loremjsfxfsfbgfffbc",
    },
    {
      id:2,
      image:"Images/french_fries.jpeg",
      name: "French Fries",
      category: "evening",
      price:40,
      description:"loremgjbjkbbbbbbbbbbbbbbbbbbbbbh",
    },
    {
      id:3,
      image:"Images/Sandwich.jpg",
      name: "Sandwich",
      category: "breakfast",
      price:30,
      description:"loremjsbgc mjgh nmjhgjvghc",
    },
    {
      id:4,
      image:"Images/aloo-pakora.jpg",
      name: "Aloo Pakoda",
      category: "breakfast",
      price:20,
      description:"loremjsbfgcnhvmjgbc",
    },
    {
      id:5,
      image:"Images/pizza.jpg",
      name: "Pizza",
      category: "dinner",
      price:80,
      description:"loremjsbcgcgnf nhfcvngvcfxvc",
    },
    {
      id:6,
      image:"Images/samosa.jpg",
      name: "Samosa",
      category: "evening",
      price:15,
      description:"loremjsbhvgfc bvv bvc bbbbftrdc",
    },
    {
      id:7,
      image:"Images/Idli.jpg",
      name: "Idli",
      category: "breakfast",
      price:20,
      description:"loremjsbvhvnvfcggfchhvgdgcc",
    },
    {
      id:8,
      image:"Images/Dosa.jpg",
      name: "Dosa",
      category: "dinner",
      price:30,
      description:"loremjsbbbhjbbbvvkbihbjc",
    },
    {
      id:9,
      image:"Images/Bread_pakoda.jpg",
      name: "Bread Pakoda",
      category: "lunch",
      price:15,
      description:"loremjsbcbbbjjbbjjbbjhjbhvh",
    },
];
export default Menu;